server:
  port: 8086

spring:
  datasource:
    username: springstudent
    password: springstudent
    url: jdbc:mysql://localhost:3306/hotel_reservation
  jpa:
    properties:
      javax:
        persistance:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off